services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - DB_PATH=/data/dogtracker.db
    volumes:
      - dbdata:/data
    ports:
      - "127.0.0.1:8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 10
  web:
    build:
      context: .
      dockerfile: nginx/Dockerfile   # builds webui and serves dist/
    ports:
      - "127.0.0.1:8081:80"
    depends_on:
      - backend
    restart: unless-stopped
volumes:
  dbdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: db